const CART = {
  CART_ADD_ITEM: "CART_ADD_ITEM",
  CART_RESET_STORAGE: "CART_RESET_STORAGE",
  CART_UPDATE_ITEM: "CART_UPDATE_ITEM",
  CART_SAVE_REQUEST: "CART_SAVE_REQUEST",
  CART_SAVE_SUCCESS: "CART_SAVE_SUCCESS",
  CART_SAVE_FAIL: "CART_SAVE_FAIL",
  CART_SAVE_RESET: "CART_SAVE_RESET",
  CART_GET_REQUEST: "CART_GET_REQUEST",
  CART_GET_SUCCESS: "CART_GET_SUCCESS",
  CART_GET_FAIL: "CART_GET_FAIL",
  CART_GET_RESET: "CART_GET_RESET",
  CART_EMPTY_REQUEST: "CART_EMPTY_REQUEST",
  CART_EMPTY_SUCCESS: "CART_EMPTY_SUCCESS",
  CART_EMPTY_FAIL: "CART_EMPTY_FAIL",
  CART_EMPTY_RESET: "CART_EMPTY_RESET",
  CART_ADDRESS_REQUEST: "CART_ADDRESS_REQUEST",
  CART_ADDRESS_SUCCESS: "CART_ADDRESS_SUCCESS",
  CART_ADDRESS_FAIL: "CART_ADDRESS_FAIL",
  CART_ADDRESS_RESET: "CART_ADDRESS_RESET",
  CART_CASH_ON_DELIVERY: "CART_CASH_ON_DELIVERY",
};

export default CART;
