const SUB = {
  SUB_LIST_REQUEST: "SUB_LIST_REQUEST",
  SUB_LIST_SUCCESS: "SUB_LIST_SUCCESS",
  SUB_LIST_FAIL: "SUB_LIST_FAIL",
  SUB_BY_SLUG_REQUEST: "SUB_BY_SLUG_REQUEST",
  SUB_BY_SLUG_SUCCESS: "SUB_BY_SLUG_SUCCESS",
  SUB_BY_SLUG_FAIL: "SUB_BY_SLUG_FAIL",
  SUB_DELETE_REQUEST: "SUB_DELETE_REQUEST",
  SUB_DELETE_SUCCESS: "SUB_DELETE_SUCCESS",
  SUB_DELETE_FAIL: "SUB_DELETE_FAIL",
  SUB_UPDATE_REQUEST: "SUB_UPDATE_REQUEST",
  SUB_UPDATE_SUCCESS: "SUB_UPDATE_SUCCESS",
  SUB_UPDATE_FAIL: "SUB_UPDATE_FAIL",
  SUB_UPDATE_RESET: "SUB_UPDATE_RESET",
  SUB_CREATE_REQUEST: "SUB_CREATE_REQUEST",
  SUB_CREATE_SUCCESS: "SUB_CREATE_SUCCESS",
  SUB_CREATE_FAIL: "SUB_CREATE_FAIL",
  SUB_CREATE_RESET: "SUB_CREATE_RESET",
};

export default SUB;
