const STRIPE = {
  STRIPE_CREATE_REQUEST: "STRIPE_CREATE_REQUEST",
  STRIPE_CREATE_SUCCESS: "STRIPE_CREATE_SUCCESS",
  STRIPE_CREATE_FAIL: "STRIPE_CREATE_FAIL",
  STRIPE_CREATE_RESET: "STRIPE_CREATE_RESET",
};

export default STRIPE;
