const COUPON = {
  COUPON_CREATE_REQUEST: "COUPON_CREATE_REQUEST",
  COUPON_CREATE_SUCCESS: "COUPON_CREATE_SUCCESS",
  COUPON_CREATE_FAIL: "COUPON_CREATE_FAIL",
  COUPON_CREATE_RESET: "COUPON_CREATE_RESET",
  COUPON_LIST_REQUEST: "COUPON_LIST_REQUEST",
  COUPON_LIST_SUCCESS: "COUPON_LIST_SUCCESS",
  COUPON_LIST_FAIL: "COUPON_LIST_FAIL",
  COUPON_DELETE_REQUEST: "COUPON_DELETE_REQUEST",
  COUPON_DELETE_SUCCESS: "COUPON_DELETE_SUCCESS",
  COUPON_DELETE_FAIL: "COUPON_DELETE_FAIL",
  COUPON_DELETE_RESET: "COUPON_DELETE_RESET",
  COUPON_APPLY_TO_CART_REQUEST: "COUPON_APPLY_TO_CART_REQUEST",
  COUPON_APPLY_TO_CART_SUCCESS: "COUPON_APPLY_TO_CART_SUCCESS",
  COUPON_APPLY_TO_CART_FAIL: "COUPON_APPLY_TO_CART_FAIL",
  COUPON_APPLY_TO_CART_RESET: "COUPON_APPLY_TO_CART_RESET",
};

export default COUPON;
