const ORDER = {
  ORDER_CREATE_REQUEST: "ORDER_CREATE_REQUEST",
  ORDER_CREATE_SUCCESS: "ORDER_CREATE_SUCCESS",
  ORDER_CREATE_FAIL: "ORDER_CREATE_FAIL",
  ORDER_CREATE_RESET: "ORDER_CREATE_RESET",
  ORDER_USER_GET_REQUEST: "ORDER_USER_GET_REQUEST",
  ORDER_USER_GET_SUCCESS: "ORDER_USER_GET_SUCCESS",
  ORDER_USER_GET_FAIL: "ORDER_USER_GET_FAIL",
  ORDER_ADMIN_GET_REQUEST: "ORDER_ADMIN_GET_REQUEST",
  ORDER_ADMIN_GET_SUCCESS: "ORDER_ADMIN_GET_SUCCESS",
  ORDER_ADMIN_GET_FAIL: "ORDER_ADMIN_GET_FAIL",
  ORDER_UPDATE_STATUS_REQUEST: "ORDER_UPDATE_STATUS_REQUEST",
  ORDER_UPDATE_STATUS_SUCCESS: "ORDER_UPDATE_STATUS_SUCCESS",
  ORDER_UPDATE_STATUS_FAIL: "ORDER_UPDATE_STATUS_FAIL",
  ORDER_UPDATE_STATUS_RESET: "ORDER_UPDATE_STATUS_RESET",
  ORDER_CREATE_COD_REQUEST: "ORDER_CREATE_COD_REQUEST",
  ORDER_CREATE_COD_SUCCESS: "ORDER_CREATE_COD_SUCCESS",
  ORDER_CREATE_COD_FAIL: "ORDER_CREATE_COD_FAIL",
  ORDER_CREATE_COD_RESET: "ORDER_CREATE_COD_RESET",
};

export default ORDER;
