const USER = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_ADD_TO_WISHLIST_REQUEST: "USER_ADD_TO_WISHLIST_REQUEST",
  USER_ADD_TO_WISHLIST_SUCCESS: "USER_ADD_TO_WISHLIST_SUCCESS",
  USER_ADD_TO_WISHLIST_FAIL: "USER_ADD_TO_WISHLIST_FAIL",
  USER_ADD_TO_WISHLIST_RESET: "USER_ADD_TO_WISHLIST_RESET",
  USER_GET_WISHLIST_REQUEST: "USER_GET_WISHLIST_REQUEST",
  USER_GET_WISHLIST_SUCCESS: "USER_GET_WISHLIST_SUCCESS",
  USER_GET_WISHLIST_FAIL: "USER_GET_WISHLIST_FAIL",
  USER_GET_WISHLIST_RESET: "USER_GET_WISHLIST_RESET",
  USER_REMOVE_WISHLIST_REQUEST: "USER_REMOVE_WISHLIST_REQUEST",
  USER_REMOVE_WISHLIST_SUCCESS: "USER_REMOVE_WISHLIST_SUCCESS",
  USER_REMOVE_WISHLIST_FAIL: "USER_REMOVE_WISHLIST_FAIL",
  USER_REMOVE_WISHLIST_RESET: "USER_REMOVE_WISHLIST_RESET",
};

export default USER;
