const FILTERS = {
  FILTERS_QUERY_TEXT: "FILTER_QUERY_TEXT",
  FILTERS_TEXT_REQUEST: "FILTERS_TEXT_REQUEST",
  FILTERS_TEXT_SUCCESS: "FILTERS_TEXT_SUCCESS",
  FILTERS_TEXT_FAIL: "FILTERS_TEXT_FAIL",
};

export default FILTERS;
